# Generated by Django 4.2.7 on 2023-11-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_slug_alter_author_biography_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='book',
        ),
    ]
